Repository infiniteopt/InfiniteOpt.jl, pull requests merged in 2021-06, with the labels that each got.

#141 Create example consumption_savings.jl
  docs/src/examples/Optimal Control/consumption_savings.jl
Labels: documentation

#145 Update Documentation Versioning
  .github/workflows/CompatHelper.yml
  docs/Project.toml
Labels: documentation

#144 Parameter Function Bug Fix
  src/macros.jl
  test/expressions.jl
Labels: bug

#147 Added variable restrictions
  docs/src/guide/constraint.md
  docs/src/guide/variable.md
  docs/src/manual/variable.md
  src/general_variables.jl
  src/infinite_variables.jl
  src/point_variables.jl
  src/semi_infinite_variables.jl
  test/derivatives.jl
  test/general_variables.jl
  test/infinite_variables.jl
  test/point_variables.jl
  test/scalar_parameters.jl
  test/semi_infinite_variables.jl
  test/utilities.jl
Labels: enhancement

#151 Discourage Finite Models
  docs/src/guide/model.md
  docs/src/index.md
  src/TranscriptionOpt/transcribe.jl
  src/optimize.jl
  test/TranscriptionOpt/transcribe.jl
  test/optimizer.jl
Labels: bug, documentation

#153 Prevent Redundant Definition
  docs/src/develop/extensions.md
  docs/src/examples/Optimal Control/consumption_savings.jl
  docs/src/examples/Optimal Control/hovercraft.jl
  docs/src/examples/Optimal Control/pandemic_control.jl
  docs/src/guide/constraint.md
  docs/src/guide/derivative.md
  docs/src/guide/optimize.md
  docs/src/guide/result.md
  docs/src/guide/transcribe.md
  docs/src/guide/variable.md
  docs/src/manual/measure.md
  docs/src/manual/transcribe.md
  docs/src/manual/variable.md
  docs/src/tutorials/quick_start.md
  src/TranscriptionOpt/measures.jl
  src/TranscriptionOpt/model.jl
  src/TranscriptionOpt/transcribe.jl
  src/datatypes.jl
  src/derivative_evaluations.jl
  src/derivatives.jl
  src/finite_variables.jl
  src/infinite_variables.jl
  src/measure_expansions.jl
  src/point_variables.jl
  src/semi_infinite_variables.jl
  src/utilities.jl
  src/variable_basics.jl
  test/TranscriptionOpt/measure.jl
  test/TranscriptionOpt/model.jl
  test/deletion.jl
  test/derivative_evaluation.jl
  test/derivatives.jl
  test/finite_variables.jl
  test/infinite_variables.jl
  test/measure_expansions.jl
  test/point_variables.jl
  test/semi_infinite_variables.jl
  test/show.jl
  test/utility_tests.jl
Labels: bug
